<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration {
 public function up(): void {
  Schema::create('workplan_progress_reports', function (Blueprint $t): void { $t->id(); $t->foreignId('mda_id'); $t->foreign('mda_id','wpr_mda_fk')->references('id')->on('mdas'); $t->foreignId('workplan_id'); $t->foreign('workplan_id','wpr_workplan_fk')->references('id')->on('workplans'); $t->foreignId('workplan_activity_id'); $t->foreign('workplan_activity_id','wpr_activity_fk')->references('id')->on('workplan_activities'); $t->string('period',16); $t->string('status',16)->default('draft'); $t->decimal('reported_expenditure',18,2)->nullable(); $t->text('achievement_summary')->nullable(); $t->text('challenges')->nullable(); $t->text('corrective_action')->nullable(); $t->text('next_period_action')->nullable(); $t->text('remarks')->nullable(); $t->foreignId('prepared_by')->nullable(); $t->foreign('prepared_by','wpr_prepared_by_fk')->references('id')->on('users')->nullOnDelete(); $t->foreignId('submitted_by')->nullable(); $t->foreign('submitted_by','wpr_submitted_by_fk')->references('id')->on('users')->nullOnDelete(); $t->timestamp('submitted_at')->nullable(); $t->foreignId('verified_by')->nullable(); $t->foreign('verified_by','wpr_verified_by_fk')->references('id')->on('users')->nullOnDelete(); $t->timestamp('verified_at')->nullable(); $t->foreignId('returned_by')->nullable(); $t->foreign('returned_by','wpr_returned_by_fk')->references('id')->on('users')->nullOnDelete(); $t->timestamp('returned_at')->nullable(); $t->text('return_reason')->nullable(); $t->json('summary')->nullable(); $t->timestamps(); $t->unique(['workplan_activity_id','period'],'wpr_activity_period_uq'); $t->index(['mda_id','workplan_id','period','status'],'wpr_mda_plan_period_status_ix'); });
  Schema::create('workplan_indicator_progresses', function (Blueprint $t): void { $t->id(); $t->foreignId('mda_id'); $t->foreign('mda_id','wip_mda_fk')->references('id')->on('mdas'); $t->foreignId('workplan_progress_report_id'); $t->foreign('workplan_progress_report_id','wip_report_fk')->references('id')->on('workplan_progress_reports')->cascadeOnDelete(); $t->foreignId('workplan_indicator_id'); $t->foreign('workplan_indicator_id','wip_indicator_fk')->references('id')->on('workplan_indicators'); $t->decimal('target_value_snapshot',18,4)->nullable(); $t->decimal('actual_value',18,4)->nullable(); $t->decimal('achievement_ratio',12,6)->nullable(); $t->text('verification_note')->nullable(); $t->timestamps(); $t->unique(['workplan_progress_report_id','workplan_indicator_id'],'wip_report_indicator_uq'); });
  Schema::create('workplan_evidence', function (Blueprint $t): void { $t->id(); $t->foreignId('mda_id'); $t->foreign('mda_id','we_mda_fk')->references('id')->on('mdas'); $t->foreignId('workplan_id'); $t->foreign('workplan_id','we_workplan_fk')->references('id')->on('workplans'); $t->foreignId('workplan_activity_id'); $t->foreign('workplan_activity_id','we_activity_fk')->references('id')->on('workplan_activities'); $t->foreignId('workplan_progress_report_id')->nullable(); $t->foreign('workplan_progress_report_id','we_report_fk')->references('id')->on('workplan_progress_reports')->nullOnDelete(); $t->string('title'); $t->string('evidence_type',16); $t->string('file_path')->nullable(); $t->string('file_mime_type')->nullable(); $t->unsignedBigInteger('file_size')->nullable(); $t->text('external_url')->nullable(); $t->text('notes')->nullable(); $t->foreignId('uploaded_by')->nullable(); $t->foreign('uploaded_by','we_uploaded_by_fk')->references('id')->on('users')->nullOnDelete(); $t->timestamps(); $t->index(['mda_id','workplan_progress_report_id'],'we_mda_report_ix'); });
 }
 public function down(): void { Schema::dropIfExists('workplan_evidence'); Schema::dropIfExists('workplan_indicator_progresses'); Schema::dropIfExists('workplan_progress_reports'); }
};
