<?php
namespace App\Domain\Workplan\Services;
use App\Domain\Workplan\Models\{WorkplanActivity,WorkplanProgressReport}; use App\Enums\{WorkplanProgressStatus,WorkplanStatus,WorkplanTargetPeriod}; use App\Models\User; use App\Services\AuditLogService; use Illuminate\Support\Facades\DB; use Illuminate\Validation\ValidationException;
class WorkplanProgressService { public function __construct(private AuditLogService $audit,private WorkplanIndicatorAchievementService $achievement){}
 public function create(WorkplanActivity $activity,string $period,User $actor):WorkplanProgressReport{$plan=$activity->objective->workplan;$this->access($actor,$activity,'update-workplan-progress');if($plan->status!==WorkplanStatus::ACTIVE)$this->fail('Only active workplans accept progress reports.');$period=WorkplanTargetPeriod::from($period)->value;return DB::transaction(function()use($activity,$plan,$period,$actor){$report=WorkplanProgressReport::query()->firstOrCreate(['workplan_activity_id'=>$activity->id,'period'=>$period],['mda_id'=>$plan->mda_id,'workplan_id'=>$plan->id,'status'=>WorkplanProgressStatus::DRAFT,'prepared_by'=>$actor->id]);if(!in_array($report->status,[WorkplanProgressStatus::DRAFT,WorkplanProgressStatus::RETURNED],true))$this->fail('A submitted or verified report already exists for this activity and period.');if($report->wasRecentlyCreated){foreach($activity->indicators as $indicator){$target=$indicator->targets()->where('period',$period)->value('target_value');$report->indicators()->create(['mda_id'=>$plan->mda_id,'workplan_indicator_id'=>$indicator->id,'target_value_snapshot'=>$target]);}$this->log('workplan.progress.created',$report,[], $report->toArray());}return $report->fresh(['activity.responsibleStaff','indicators.indicator','evidence']);});}
 public function update(WorkplanProgressReport $r,array $data,User $actor):WorkplanProgressReport{$this->access($actor,$r->activity,'update-workplan-progress');$this->editable($r);if(isset($data['reported_expenditure'])&&(float)$data['reported_expenditure']<0)$this->fail('Reported expenditure cannot be negative.');$before=$r->toArray();$r->fill(collect($data)->only(['reported_expenditure','achievement_summary','challenges','corrective_action','next_period_action','remarks'])->all())->save();$this->log('workplan.progress.updated',$r,$before,$r->toArray());return $r->fresh(['activity.responsibleStaff','indicators.indicator','evidence']);}
 public function syncIndicators(WorkplanProgressReport $r,array $rows,User $actor):WorkplanProgressReport{$this->access($actor,$r->activity,'update-workplan-progress');$this->editable($r);foreach($rows as $row){$p=$r->indicators()->where('workplan_indicator_id',$row['workplan_indicator_id'])->with('indicator')->first();if(!$p)$this->fail('Every indicator must belong to this report activity.');$p->fill(['actual_value'=>$row['actual_value']??null,'verification_note'=>$row['verification_note']??null,'achievement_ratio'=>$this->achievement->ratio($p->indicator,$p->target_value_snapshot,$row['actual_value']??null)])->save();}$this->log('workplan.progress.indicators_synced',$r,[],[]);return $r->fresh(['indicators.indicator']);}
 public function submit(WorkplanProgressReport $r,User $actor):WorkplanProgressReport{$this->access($actor,$r->activity,'update-workplan-progress');$this->editable($r);if($r->activity->objective->workplan->status!==WorkplanStatus::ACTIVE)$this->fail('Only active workplans may submit progress.');if($r->indicators()->whereHas('indicator',fn($q)=>$q->where('is_required',true))->whereNull('actual_value')->exists())$this->fail('All required indicator actuals must be supplied.');$before=$r->toArray();$event=$r->status===WorkplanProgressStatus::RETURNED?'workplan.progress.resubmitted':'workplan.progress.submitted';$r->forceFill(['status'=>WorkplanProgressStatus::SUBMITTED,'submitted_by'=>$actor->id,'submitted_at'=>now()])->save();$this->log($event,$r,$before,$r->toArray());return $r->fresh();}
 public function return(WorkplanProgressReport $r,string $reason,User $actor):WorkplanProgressReport{$this->access($actor,$r->activity,'verify-workplan-progress');if($r->status!==WorkplanProgressStatus::SUBMITTED)$this->fail('Only submitted reports may be returned.');$before=$r->toArray();$r->forceFill(['status'=>WorkplanProgressStatus::RETURNED,'returned_by'=>$actor->id,'returned_at'=>now(),'return_reason'=>$reason])->save();$this->log('workplan.progress.returned',$r,$before,$r->toArray());return $r->fresh();}
 public function verify(WorkplanProgressReport $r,User $actor):WorkplanProgressReport{$this->access($actor,$r->activity,'verify-workplan-progress');if($r->status!==WorkplanProgressStatus::SUBMITTED)$this->fail('Only submitted reports may be verified.');$before=$r->toArray();$r->forceFill(['status'=>WorkplanProgressStatus::VERIFIED,'verified_by'=>$actor->id,'verified_at'=>now()])->save();$this->log('workplan.progress.verified',$r,$before,$r->toArray());return $r->fresh();}
 private function editable(WorkplanProgressReport $r):void{if(!in_array($r->status,[WorkplanProgressStatus::DRAFT,WorkplanProgressStatus::RETURNED],true))$this->fail('Only draft or returned reports may be edited.');} private function access(User $u,WorkplanActivity $a,string $permission):void{abort_unless($u->can($permission)&&$u->canAccessMda($a->mda_id)&&($a->department_id===null||$u->canAccessDepartment($a->department_id)),403);} private function fail(string $m):never{throw ValidationException::withMessages(['progress'=>$m]);} private function log(string $e,WorkplanProgressReport $r,array $b,array $a):void{$this->audit->log($e,$r,$b,$a,['mda_id'=>$r->mda_id,'workplan_id'=>$r->workplan_id,'activity_id'=>$r->workplan_activity_id,'progress_report_id'=>$r->id,'period'=>$r->period->value]);}}
