<?php
namespace App\Domain\Workplan\Services;
use App\Domain\Approval\Services\ApprovalWorkflowService;
use App\Domain\Workplan\Models\Workplan;
use App\Enums\WorkplanStatus;
use App\Models\User;
use App\Services\AuditLogService;
use Illuminate\Support\Facades\DB;
use Illuminate\Validation\ValidationException;

class WorkplanWorkflowService {
 public function __construct(private ApprovalWorkflowService $approval, private AuditLogService $audit) {}
 public function submit(Workplan $plan, User $actor): Workplan { $this->assertAccess($plan,$actor,'submit-workplans'); $this->validate($plan); if(!in_array($plan->status,[WorkplanStatus::DRAFT,WorkplanStatus::RETURNED],true)) $this->fail('This workplan cannot be submitted.'); return DB::transaction(function()use($plan,$actor){$before=$plan->toArray();$workflow=$this->approval->submit($plan,'workplan_approval',$actor,[['reviewer_role'=>'Approval Officer','metadata'=>['required_permission'=>'review-workplans']],['reviewer_role'=>'Approval Officer','metadata'=>['required_permission'=>'approve-workplans']]],['mda_id'=>$plan->mda_id,'year'=>$plan->year]);$plan->forceFill(['status'=>WorkplanStatus::SUBMITTED,'submitted_by'=>$actor->id,'submitted_at'=>now()])->save();$this->log($plan,$before,$plan->toArray(),($before['status'] ?? null)===WorkplanStatus::RETURNED->value?'workplan.resubmitted':'workplan.submitted',['workflow_id'=>$workflow->id]);return $plan->fresh('approvalWorkflow.steps');});}
 public function approve(Workplan $plan,User $actor):Workplan{$this->assertStepAccess($plan,$actor);return DB::transaction(function()use($plan,$actor){$before=$plan->toArray();$workflow=$this->approval->approveStep($plan->approvalWorkflow,$actor);$final=$workflow->status==='approved';$plan->forceFill($final?['status'=>WorkplanStatus::APPROVED,'approved_by'=>$actor->id,'approved_at'=>now()]:['status'=>WorkplanStatus::UNDER_REVIEW])->save();$this->log($plan,$before,$plan->toArray(),$final?'workplan.approved':'workplan.reviewed',['workflow_id'=>$workflow->id]);return $plan->fresh('approvalWorkflow.steps');});}
 public function return(Workplan $plan,User $actor,string $comment):Workplan{$this->assertStepAccess($plan,$actor);return DB::transaction(function()use($plan,$actor,$comment){$before=$plan->toArray();$w=$this->approval->returnForCorrection($plan->approvalWorkflow,$actor,$comment);$plan->forceFill(['status'=>WorkplanStatus::RETURNED])->save();$this->log($plan,$before,$plan->toArray(),'workplan.returned',['workflow_id'=>$w->id,'reason'=>$comment]);return $plan->fresh('approvalWorkflow.steps');});}
 public function reject(Workplan $plan,User $actor,string $comment):Workplan{$this->assertStepAccess($plan,$actor);return DB::transaction(function()use($plan,$actor,$comment){$before=$plan->toArray();$w=$this->approval->reject($plan->approvalWorkflow,$actor,$comment);$plan->forceFill(['status'=>WorkplanStatus::REJECTED])->save();$this->log($plan,$before,$plan->toArray(),'workplan.rejected',['workflow_id'=>$w->id,'reason'=>$comment]);return $plan->fresh('approvalWorkflow.steps');});}
 public function activate(Workplan $plan,User $actor):Workplan{$this->assertAccess($plan,$actor,'approve-workplans');if($plan->status!==WorkplanStatus::APPROVED||$plan->approvalWorkflow?->status!=='approved')$this->fail('Only fully approved workplans may be activated.');return DB::transaction(function()use($plan,$actor){$locked=Workplan::query()->where('mda_id',$plan->mda_id)->where('year',$plan->year)->lockForUpdate()->get();$active=$locked->where('status',WorkplanStatus::ACTIVE);foreach($active as $old){if($plan->supersedes_workplan_id !== $old->id)$this->fail('This approved workplan does not supersede the active revision.');$beforeOld=$old->toArray();$old->forceFill(['status'=>WorkplanStatus::SUPERSEDED,'superseded_at'=>now(),'superseded_by_workplan_id'=>$plan->id])->save();$this->log($old,$beforeOld,$old->toArray(),'workplan.superseded',['replacement_workplan_id'=>$plan->id]);}if($active->isEmpty() && $plan->supersedes_workplan_id !== null)$this->fail('The amendment source is no longer the active revision.');$before=$plan->toArray();$plan->forceFill(['status'=>WorkplanStatus::ACTIVE,'activated_by'=>$actor->id,'activated_at'=>now()])->save();$this->log($plan,$before,$plan->toArray(),'workplan.activated');return $plan->fresh();});}
 public function close(Workplan $plan,User $actor):Workplan{$this->assertAccess($plan,$actor,'approve-workplans');if($plan->status!==WorkplanStatus::ACTIVE)$this->fail('Only active workplans may be closed.');$before=$plan->toArray();$plan->forceFill(['status'=>WorkplanStatus::CLOSED,'closed_by'=>$actor->id,'closed_at'=>now()])->save();$this->log($plan,$before,$plan->toArray(),'workplan.closed');return $plan->fresh();}
 public function amendment(Workplan $source,User $actor,string $reason):Workplan{$this->assertAccess($source,$actor,'amend-workplans');if($source->status!==WorkplanStatus::ACTIVE)$this->fail('Only active workplans may be amended.');return DB::transaction(function()use($source,$actor,$reason){$max=Workplan::query()->where('mda_id',$source->mda_id)->where('year',$source->year)->lockForUpdate()->max('revision_no');$new=Workplan::query()->create(['mda_id'=>$source->mda_id,'year'=>$source->year,'revision_no'=>$max+1,'supersedes_workplan_id'=>$source->id,'title'=>$source->title,'description'=>$source->description,'status'=>WorkplanStatus::DRAFT,'prepared_by'=>$actor->id,'amendment_reason'=>$reason]);$source->load('objectives.activities.supportAssignments','objectives.activities.indicators.targets');foreach($source->objectives as $o){$no=$new->objectives()->create($o->only(['mda_id','department_id','code','title','description','priority','performance_weight','sort_order']));foreach($o->activities as $a){$na=$no->activities()->create($a->only(['mda_id','department_id','responsible_staff_id','activity_code','title','description','expected_output','start_date','end_date','planned_cost','funding_source','status','performance_weight','remarks','sort_order']));foreach($a->supportAssignments as $s)$na->supportAssignments()->create($s->only(['mda_id','staff_id','role']));foreach($a->indicators as $i){$ni=$na->indicators()->create($i->only(['mda_id','code','indicator','unit','baseline_value','annual_target_value','target_mode','direction','weight','sort_order','is_required']));foreach($i->targets as $t)$ni->targets()->create($t->only(['mda_id','period','target_value']));}}}$this->log($new,[],$new->toArray(),'workplan.amendment_created',['source_workplan_id'=>$source->id,'source_revision_no'=>$source->revision_no,'new_workplan_id'=>$new->id,'new_revision_no'=>$new->revision_no,'amendment_reason'=>$reason]);return $new;});}
 private function validate(Workplan $p):void{$p->load('objectives.activities.indicators.targets');if($p->objectives->isEmpty()||$p->objectives->flatMap->activities->isEmpty())$this->fail('At least one objective and activity are required.');foreach($p->objectives->flatMap->activities as $a){if(!$a->responsible_staff_id||$a->indicators->isEmpty())$this->fail('Every activity needs a responsible staff member and indicator.');foreach($a->indicators as $i)if($i->is_required&&$i->annual_target_value===null)$this->fail('Required indicators need annual targets.');}}
 private function assertAccess(Workplan $p,User $u,string $permission):void{abort_unless($u->can($permission)&&$u->canAccessMda($p->mda_id),403);}
 private function assertStepAccess(Workplan $p,User $u):void{$workflow=$p->approvalWorkflow()->with('steps')->first();$step=$workflow?->steps->firstWhere('status','pending');abort_unless($u->canAccessMda($p->mda_id)&&$step?->isActionableBy($u),403);}
 private function fail(string $m):never{throw ValidationException::withMessages(['workplan'=>$m]);}
 private function log(Workplan $p,array $before,array $after,string $event,array $extra=[]):void{$this->audit->log($event,$p,$before,$after,['source'=>'workplan_workflow','mda_id'=>$p->mda_id,'workplan_id'=>$p->id,'year'=>$p->year,'revision_no'=>$p->revision_no,...$extra]);}
}
